[package]
version = "0.6.4"
authors = ["Christian Douven <chridou@users.noreply.github.com>"]
description = "metrics for application monitoring"
documentation = "https://docs.rs/metrix"
homepage = "https://github.com/chridou/metrix"
keywords = ["metrics", "monitoring", "alert"]
license = "Apache-2.0/MIT"
name = "metrix"
readme = "README.md"
repository = "https://github.com/chridou/metrix"

[badges]
[badges.travis-ci]
branch = "master"
repository = "chridou/metrix"

[dependencies]
exponential-decay-histogram = "0.1.0"
json = "0.11.0"
metrics = "0.2.0"